/*
 * Copyright (C) Qatar Insurance Group, PO Box 666, Doha, Qatar
 * All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 */
if("undefined"===typeof jQuery)throw Error("Util's JavaScript requires jQuery");var bootstrap3_enabled="function"==typeof $().emulateTransitionEnd;if(!bootstrap3_enabled)throw Error("Util's JavaScript requires Bootstrap3");
function applyAjaxResponseError(a,b){a=$.trim(a);var c=!1;if(20<=a.length){var d=a.substring(0,20);"ERROR_FOUND_CODE=405"===d?(c=!0,a=a.substring(20,a.length),""===a&&(a="Given inputs are invalid!"),$("#"+b).html(a).show(),goToByScroll(b)):-1!=a.indexOf("Struts Problem Report")?(c=!0,$("#"+b).html(a).show(),goToByScroll(b)):42<=a.length&&(d=a.substring(27,37),"ERROR_PAGE"===d&&(c=!0,$("#"+b).html(a).show(),goToByScroll(b)))}return c}
function goToByScroll(a){if(""==a||!$("#"+a).length)return!1;a=a.replace("link","");$("html,body").animate({scrollTop:$("#"+a).offset().top-50},"fast");return!1}
function block(a){var b={message:'<div class="preloader"><div class="spinner-layer pl-red"> <div class="circle-clipper left">   <div class="circle"></div></div>  <div class="circle-clipper right">      <div class="circle"></div>   </div></div></div>',fadeIn:0,fadeOut:0,baseZ:10002,css:{border:0,padding:0,backgroundColor:"transparent"},overlayCSS:{backgroundColor:"#fff",opacity:.8,cursor:"wait"}};a?$("#"+a).block(b):$.blockUI(b)}function unblock(a){a?$("#"+a).unblock():$.unblockUI({fadeOut:10})}
$.fn.reloadDT=function(a){a?$(this).DataTable().ajax.url(a).load():$(this).DataTable().ajax.reload(null,!1)};
$.fn.tabs=function(){var a=this;return{add:function(b,c){var d=Math.abs(Math.random()).toString().replace(".","");$(a).find(".tab-list > li").removeClass("active");$(a).find(".tab-content > div").removeClass("fade in active");$(a).find(".tab-list").append($('<li class="active"><a href="#tab'+d+'" role="tab" data-toggle="tab">'+b+'<button class="close" type="button" title="Close" style="margin-left: 5px;">\u00d7</button></a></li>'));$(a).find(".tab-content").append($('<div class="tab-pane fade in active" id="tab'+
d+'"></div>').html(c));$(a).on("click",".close",function(){var b=$(this).parents("a").attr("href");$(this).parents("li").remove();$(b).remove();$(a).find(".tab-list a:first").tab("show")})}}};$.fn.serializeObject=function(){var a={},b=this.serializeArray();$.each(b,function(){void 0!==a[this.name]?(a[this.name].push||(a[this.name]=[a[this.name]]),a[this.name].push(this.value||"")):a[this.name]=this.value||""});return a};
$.fn.modals=function(){var a=this;return{lg:function(b){$(a).find(".modal-dialog").removeClass("modal-sm modal-mm").addClass("modal-lg");$(a).find(".modal-content").empty().html(b);$(a).modal("show")},mm:function(b){$(a).find(".modal-dialog").removeClass("modal-lg modal-sm modal-mx").addClass("modal-mm");$(a).find(".modal-content").empty().html(b);$(a).modal("show")},sm:function(b){$(a).find(".modal-dialog").removeClass("modal-lg modal-mm modal-mx").addClass("modal-sm");$(a).find(".modal-content").empty().html(b);
$(a).modal("show")},mx:function(b){$(a).find(".modal-dialog").removeClass("modal-lg modal-mm modal-sm").addClass("modal-mx");$(a).find(".modal-content").empty().html(b);$(a).modal("show")}}};
$.fn.openpage=function(a){INIT={init:function(a,c){var b=this;a.on("click",function(){var a=b.getOptions($(this),a);block(a.lodingBlock);setTimeout(function(){$.ajax({type:"POST",async:!1,url:APP_CONFIG.context+a.url,success:function(b){$("#"+a.lodingBlock).empty().html(b)},error:function(a,b,c){alert("Error: "+c)},complete:function(){unblock(a.lodingBlock)}})},0)})},getDefaults:function(){return this.DEFAULTS},getOptions:function(a,c){return c=$.extend({},this.getDefaults(),a.data(),c)},DEFAULTS:{url:null,
lodingBlock:"block_body",contentBlock:"block_body"}};INIT.init(this,a)};function timeago(){$("[data-timeago]").each(function(){$(this).html(moment($(this).data("timeago"),"DD/MM/YYYY HH:mm").fromNow())})}TIMEAGO={init:function(){timeago();var a;a||(a=setInterval(function(){timeago()},3E4))}};
var getDuration=function(a,b){var c=new Date(b-a),d=new Date(0);return{getHours:function(){return c.getHours()-d.getHours()},getMinutes:function(){return c.getMinutes()-d.getMinutes()},getMilliseconds:function(){return c.getMilliseconds()-d.getMilliseconds()},lpad:function(a,b,c){if(!a||!b||a.length>=c)return a;c=(c-a.toString().length)/b.length;for(var d=0;d<c;d++)a=b+a;return a},rpad:function(a,b,c){if(!a||!b||a.length>=c)return a;c=(c-a.length)/b.length;for(var d=0;d<c;d++)a+=b;return a},getTimeDiff:function(){return this.getHours()+
"."+this.lpad(this.getMinutes(),"0",2)},toString:function(){return this.getHours()+":"+this.lpad(this.getMinutes(),"0",2)+":"+this.lpad(this.getMilliseconds(),"0",2)}}};function fixedEncodeURIComponent(str){return encodeURIComponent(str).replace(/[!'()*]/g,function(c){return '%'+c.charCodeAt(0).toString(16);});}